name: Matrix
on: push

jobs:
  node-version:
    strategy:
      matrix:
        node_version: [6,8,10]
      fail-fast: true
    steps:
      - name: Log node node-version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: 6
      - name: Log node version
        run: node -v